### ISSUE TITLE
gpu not working

### ISSUE THREAD

**Issue by HappyDog2012** [smxl/ore-v2-mine#1]
谢谢大神的脚本工具，thanks for ur scripts and tools big guy, I successfully executed the cargo build with features=gpu (removed the # ahead before gpu in cargo.toml) and run with the gpu commands, but gpu (rtx 3070 Laptop) did not work, cpu (r7 5800h) was working lol, any idea why? is that the drillx problem? thank u again my man, love u

**Comment by HappyDog2012** [comment]
> 谢谢大神的脚本工具，thanks for ur scripts and tools big guy, I successfully executed the cargo build with features=gpu (removed the # ahead before gpu in cargo.toml) and run with the gpu commands, but gpu (rtx 3070 Laptop) did not work, cpu (r7 5800h) was working lol, any idea why? is that the drillx problem? thank u again my man, love u
nvidia gpu driver and cuda tools all installed

**Comment by smxl** [comment]
你需要更新仓库重新编译 https://github.com/smxl/ore-v2-mine#ore-update GPU 特性已被官方抛弃

**Comment by HappyDog2012** [comment]
> 你需要更新仓库重新编译 https://github.com/smxl/ore-v2-mine#ore-update GPU 特性已被官方更新算法后移除

谢谢大神！
